version: '3.7'
name: astraeus

services:
  database:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: astraeus
      POSTGRES_USER: astraeus
      POSTGRES_DB: astraeus-db
    ports:
      - 5432:5432
    volumes:
      - "astraeus-db:/var/lib/postgresql/data"
      - "./init-scripts:/docker-entrypoint-initdb.d"
    command: ["postgres", "-c", "log_statement=all"]

volumes:
  astraeus-db:
    external: true
